### ISSUE TITLE
How do you know what the game is expecting for a response?

### ISSUE THREAD

**Issue by Colanderp** [InvoxiPlayGames/ReFused#1]
I am trying to work on this repo and build out more features.
Hoping to get setup with AWS Gamelift and allow for co-op freestyles working in the end, but focusing on the shop for now.
By chance do you have the source code of the game? Or do you just already have examples of requests and responses from the original API?

I got the diamond store responses correctly after trial and error:
```
const response = {
    "results": {
          "featured_items": [],
          "store_items": []
    }
};
```

where items are:
```
const item = {
    "uuid": "cd371946-a2dd-488c-937a-5ac64560fee0",
    "assets": [],
    "start_date": "2023-08-05T13:00:00Z",
    "end_date": "2024-08-05T13:00:00Z",
    "price": 0,
    "is_owned": false,
    "featured_image_url": null,
    "featured_image_medium_url": null,
    "featured_image_small_url": null
}
```

where assets are:
```
const asset = {
    "asset_name": "Chorus_01",
    "asset_type": "AudioEffects"
}
```

And got the diamond store to give every single diamond item.
But I am not having luck on the real store, so I was wondering how you got this all setup and knew what the responses were for promotion, recordings, user search, etc. 

Any insight would be really helpful and appreciated!

**Comment by InvoxiPlayGames** [comment]
I have a few archived HTTPS captures of the server from before it went down, doing everything I could in-game. (I also have a few Wireshark captures of the online co-op and diamond stage, but it'll be a while before I understand those.)

I'm also able to reverse engineer the game, if anything can't be figured out.

What do you mean "not having luck on the real store?"

**Comment by Colanderp** [comment]
Sorry I can be clearer.
I am trying to mock out the store since I got the diamond store mocked now as well.
While the store or interacting with it actually does anything, I was trying to get cards to show in the store from any response.
It hits /api/store/get_list/ and I've just been trying to return anything from that to get a card to show in the store:
![image](https://github.com/InvoxiPlayGames/ReFused/assets/50305955/eb4b6d9b-1db9-4112-85c0-2852e64ed52d)

As I was able to get stuff in the diamond store:
![image](https://github.com/InvoxiPlayGames/ReFused/assets/50305955/22df7414-50fa-48cb-9212-33bbe4120ca7)

While I am not even sure getting something in the DLC store would be possible as it does seem to try to hit:
/static/pc_store_asset.bin as well and I do not have those files.

Would you by chance be willing to share those HTTPS captures and Wireshark captures? 

I have tried to get any sort of information by digging through the game files without getting much luck, nor was I able to actually get any code out of the game to find where/how these responses are being used, but I would like to continue working on this. Its just hard unless I have any kind of insight into what the game is expecting for responses.

**Comment by InvoxiPlayGames** [comment]
Oh, the DLC store relies on responses from Steam. The game's server only returns some metadata and a Steam app ID. The PC store asset is a static file with the DLC metadata in it, the game was updated to directly include this around the time of the discontinuation.

**Comment by Colanderp** [comment]
Interesting, that might be a dead-end then for mocking anything. 
The thing I am using for digging through the paks doesn't seem to be a viable way to get them from the game files, might look for something else to see if I can find it at all.
The store is not that big of deal. Can't buy the DLC anyway, so not much it could do. 
Diamond store works and gives all the items, that is good enough for me for now.

I am still interested in getting some sort of multiplayer working as well.
Would it be possible for you to share those saved captures you got before the game went down?

Thanks for responding to all this btw.

**Comment by InvoxiPlayGames** [comment]
I'd have to figure out how to strip the sensitive information from the captures, but I'd love to share them when I can get around to it. The captures may be useless though - I wasn't able to figure out whether the connection with the game lobby was encrypted or not after the web services API gives out the IP address of the newly made game lobby. If it is, and the key isn't recoverable, then the captures are useless.

**Comment by Colanderp** [comment]
That make sense. Hopefully it is not encrypted. Definitely not an easy task.
No rush of course, please let me know how it all goes whenever you get the time.
Or if you are able to strip any sensitive data and share them I'd love to help out as well.

Honestly looking at how difficult it may be to get multiplayer back, might be quicker to make FUSER from the ground up for me at this point.

I can close this issue.
You've answered my questions, thank you for your time.
Please again keep me updated on if you ever get around to be able to share the captures.

**Comment by supersonic124** [comment]
I was wondering if there's any chance you could release your version with the everything diamond store packs? There's still a bunch of unobtainable items that weren't included in the official harmonix ones before the shutdown, like the robot and alligator costumes
